package com.erp.qualitascareapi.notificacao.enums;

public enum TipoNotificacao {
    TEMPERATURA_GELADEIRA_ALERTA,
    TEMPERATURA_GELADEIRA_NAO_CONFORME,
    MONITORAMENTO_AMBIENTAL_ALERTA,
    MONITORAMENTO_AMBIENTAL_NAO_CONFORME,
    DISPOSITIVO_IOT_OFFLINE
}
