package com.erp.qualitascareapi.iam.enums;

public enum OrgRoleType {
    QUALIDADE_GERENTE,
    ENFERMAGEM_GERENTE,
    EDUCACAO_PERMANENTE_GERENTE,
    GERENCIA_SETOR,
    JURIDICO,
    DIRETOR_TECNICO,
    DIRETOR_CLINICO,
    DIRETORIA_INSTITUCIONAL
}
