package com.erp.qualitascareapi.security.enums;

public enum ResourceType {
    INDICADOR,
    AUDITORIA,
    NAO_CONFORMIDADE,
    PROTOCOLO,
    CAPACITACAO,
    PGRSS,
    USUARIO,
    DASHBOARD,
    DOCUMENTO,
    DOCUMENTO_VERSAO,
    DOCUMENTO_ACK,
    DOCUMENTO_ALTERACAO,
    CME_AUTOCLAVE,
    IAM_TENANT,
    IAM_USER,
    IAM_SETOR,
    IAM_ORG_ROLE_ASSIGNMENT,
    IAM_PROFILE,
    HR_CARGO,
    HR_COLABORADOR,
    SECURITY_ROLE,
    SECURITY_PERMISSION,
    SECURITY_ROLE_PERMISSION,
    SECURITY_POLICY,
    SECURITY_USER_PERMISSION_OVERRIDE
}
