package com.erp.qualitascareapi.pgrss.enums;

public enum TipoNaoConformidade {
    SEGREGACAO_INCORRETA,
    ACONDICIONAMENTO_INADEQUADO,
    IDENTIFICACAO_AUSENTE,
    COLETOR_INADEQUADO,
    EXCESSO_CAPACIDADE,
    RESIDUO_INFECTANTE_COMUM,
    PERFUROCORTANTE_FORA_CAIXA,
    ARMAZENAMENTO_INADEQUADO,
    COLETA_FORA_ROTA,
    OUTRO
}
